replicaCount: 1

image:
  repository: ghcr.io/mikavl/slapd
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

clusterDomain: cluster.local

suffix: dc=home,dc=arpa

persistence:
  storageClassName: ""
  size: 1Gi

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 10000
  runAsGroup: 10000
  fsGroup: 10000

securityContext:
  capabilities:
   drop:
   - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 636

resources:
  slapd:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
