apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slapd.serviceAccountName" . }}
  labels:
    {{- include "slapd.labels" . | nindent 4 }}
data:
  consumer.ldif: |
    dn: cn=config
    objectClass: olcGlobal
    cn: config
    olcArgsFile: /run/slapd/slapd.args
    olcDisallows: bind_anon
    olcPasswordCryptSaltFormat: $6$%.16s
    olcPidFile: /run/slapd/slapd.pid
    olcToolThreads: 1

    dn: cn=module,cn=config
    objectClass: olcModuleList
    cn: module
    olcModulePath: /usr/lib/ldap
    olcModuleLoad: back_mdb
    olcModuleLoad: accesslog
    olcModuleLoad: back_monitor
    olcModuleLoad: memberof
    olcModuleLoad: refint
    olcModuleLoad: syncprov

    dn: olcDatabase={-1}frontend,cn=config
    objectClass: olcDatabaseConfig
    objectClass: olcFrontendConfig
    olcDatabase: {-1}frontend
    olcPasswordHash: {CRYPT}
    olcRequires: authc
    olcAccess: to dn.exact=""
      by * read
    olcAccess: to dn.base="cn=Subschema"
      by * read

    dn: olcDatabase={0}config,cn=config
    objectClass: olcDatabaseConfig
    olcDatabase: {0}config
    olcRootDN: cn=admin,cn=config
    olcAccess: to *
      by dn.exact="{{ include "slapd.identityDN" . }}" manage
      by * break

    dn: cn=schema,cn=config
    objectClass: olcSchemaConfig
    cn: schema

    include: file:///etc/ldap/schema/core.ldif
    include: file:///etc/ldap/schema/cosine.ldif
    include: file:///etc/ldap/schema/rfc2307bis.ldif
    include: file:///etc/ldap/schema/inetorgperson.ldif

    dn: olcDatabase={1}monitor,cn=config
    objectClass: olcDatabaseConfig
    olcDatabase: {1}monitor
    olcMonitoring: FALSE
    olcAccess: to *
      by dn.exact="{{ include "slapd.identityDN" . }}" read
      by * break

    dn: olcDatabase={2}mdb,cn=config
    objectClass: olcDatabaseConfig
    objectClass: olcMdbConfig
    olcDatabase: {2}mdb
    olcDbMaxSize: 1073741824
    olcDbCheckpoint: 512 30
    olcSuffix: {{ .Values.suffix }}
    olcDbDirectory: /data
    olcMonitoring: TRUE
    olcRootDN: cn=admin,{{ .Values.suffix }}
    olcDbIndex: automountKey,automountMapName,cn,gidNumber,member,memberOf,memberUid,objectClass,uid,uidNumber eq
    olcDbIndex: entryCSN,entryUUID eq
    olcSyncRepl: rid=000
      provider="{{ include "slapd.providerURL" . }}"
      type=refreshAndPersist
      searchbase="{{ .Values.suffix }}"
      bindmethod=simple
      binddn="{{ include "slapd.replicatorDN" . }}"
      credentials="@CREDENTIALS@"
      syncdata=accesslog
      logbase="cn=accesslog"
      logfilter="(&(objectClass=auditWriteObject)(reqResult=0))"
      schemachecking=on
      retry="10 +"
    olcAccess: to attrs=userPassword
      by dn.exact="{{ include "slapd.identityDN" . }}" manage
      by dn.exact="{{ include "slapd.managerDN" . }}" write
      by self write
      by anonymous auth
      by * none
    olcAccess: to attrs=shadowLastChange
      by dn.exact="{{ include "slapd.identityDN" . }}" manage
      by dn.exact="{{ include "slapd.managerDN" . }}" write
      by self write
      by * none
    olcAccess: to *
      by dn.exact="{{ include "slapd.identityDN" . }}" manage
      by dn.exact="{{ include "slapd.managerDN" . }}" write
      by dn.one="{{ include "slapd.servicesOU" . }}" read
      by dn.one="{{ include "slapd.usersOU" . }}" read
      by * break

    dn: olcOverlay=memberof,olcDatabase={2}mdb,cn=config
    objectClass: olcConfig
    objectClass: olcMemberOf
    objectClass: olcOverlayConfig
    objectClass: top
    olcOverlay: memberof
    olcMemberOfRefInt: TRUE
    olcMemberOfGroupOC: groupOfMembers
    olcMemberOfMemberAD: member
    olcMemberOfMemberOfAD: memberOf

    dn: olcOverlay=refint,olcDatabase={2}mdb,cn=config
    objectClass: olcConfig
    objectClass: olcRefintConfig
    objectClass: olcOverlayConfig
    objectClass: top
    olcOverlay: refint
    olcRefintAttribute: member memberOf

  haproxy.cfg: |
    global
      log stdout format raw local0

    defaults
      log     global
      mode    tcp
      option  tcplog
      timeout connect 5000
      timeout client  50000
      timeout server  50000

    frontend ldaps
      bind *:10636 ssl crt /certs/external/cert.pem
      default_backend ldapi

    frontend ldaps-syncrepl
      bind *:10637 ssl crt /certs/internal/cert.pem
      default_backend ldapi

    backend ldapi
      server slapd unix@/run/slapd/ldapi

  provider.ldif: |
    dn: cn=config
    objectClass: olcGlobal
    cn: config
    olcArgsFile: /run/slapd/slapd.args
    olcDisallows: bind_anon
    olcPasswordCryptSaltFormat: $6$%.16s
    olcPidFile: /run/slapd/slapd.pid
    olcToolThreads: 1

    dn: cn=module,cn=config
    objectClass: olcModuleList
    cn: module
    olcModulePath: /usr/lib/ldap
    olcModuleLoad: back_mdb
    olcModuleLoad: accesslog
    olcModuleLoad: back_monitor
    olcModuleLoad: memberof
    olcModuleLoad: refint
    olcModuleLoad: syncprov

    dn: olcDatabase={-1}frontend,cn=config
    objectClass: olcDatabaseConfig
    objectClass: olcFrontendConfig
    olcDatabase: {-1}frontend
    olcPasswordHash: {CRYPT}
    olcRequires: authc
    olcAccess: to dn.exact=""
      by * read
    olcAccess: to dn.base="cn=Subschema"
      by * read

    dn: olcDatabase={0}config,cn=config
    objectClass: olcDatabaseConfig
    olcDatabase: {0}config
    olcRootDN: cn=admin,cn=config
    olcAccess: to *
      by dn.exact="{{ include "slapd.identityDN" . }}" manage
      by * break

    dn: cn=schema,cn=config
    objectClass: olcSchemaConfig
    cn: schema

    include: file:///etc/ldap/schema/core.ldif
    include: file:///etc/ldap/schema/cosine.ldif
    include: file:///etc/ldap/schema/rfc2307bis.ldif
    include: file:///etc/ldap/schema/inetorgperson.ldif

    dn: olcDatabase={1}monitor,cn=config
    objectClass: olcDatabaseConfig
    olcDatabase: {1}monitor
    olcMonitoring: FALSE
    olcAccess: to *
      by dn.exact="{{ include "slapd.identityDN" . }}" read
      by * break

    dn: olcDatabase={2}mdb,cn=config
    objectClass: olcDatabaseConfig
    objectClass: olcMdbConfig
    olcDatabase: {2}mdb
    olcDbMaxSize: 1073741824
    olcDbDirectory: /data/accesslog
    olcSuffix: cn=accesslog
    olcRootDN: cn=admin,cn=accesslog
    olcDbIndex: entryCSN,objectClass,reqEnd,reqResult,reqStart,reqDN eq
    olcAccess: to *
      by dn.exact="{{ include "slapd.identityDN" . }}" read
      by dn.exact="{{ include "slapd.replicatorDN" . }}" read
      by * break

    dn: olcOverlay=syncprov,olcDatabase={2}mdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcSyncProvConfig
    olcOverlay: syncprov
    olcSpNoPresent: TRUE
    olcSpReloadHint: TRUE

    dn: olcDatabase={3}mdb,cn=config
    objectClass: olcDatabaseConfig
    objectClass: olcMdbConfig
    olcDatabase: {3}mdb
    olcDbMaxSize: 1073741824
    olcDbCheckpoint: 512 30
    olcSuffix: {{ .Values.suffix }}
    olcDbDirectory: /data
    olcMonitoring: TRUE
    olcRootDN: cn=admin,{{ .Values.suffix }}
    olcDbIndex: automountKey,automountMapName,cn,gidNumber,member,memberOf,memberUid,objectClass,uid,uidNumber eq
    olcDbIndex: entryCSN,entryUUID eq
    olcAccess: to attrs=userPassword
      by dn.exact="{{ include "slapd.identityDN" . }}" manage
      by dn.exact="{{ include "slapd.managerDN" . }}" write
      by dn.exact="{{ include "slapd.replicatorDN" . }}" read
      by self write
      by anonymous auth
      by * none
    olcAccess: to attrs=shadowLastChange
      by dn.exact="{{ include "slapd.identityDN" . }}" manage
      by dn.exact="{{ include "slapd.managerDN" . }}" write
      by dn.exact="{{ include "slapd.replicatorDN" . }}" read
      by self write
      by * none
    olcAccess: to *
      by dn.exact="{{ include "slapd.identityDN" . }}" manage
      by dn.exact="{{ include "slapd.managerDN" . }}" write
      by dn.exact="{{ include "slapd.replicatorDN" . }}" read
      by dn.one="{{ include "slapd.servicesOU" . }}" read
      by dn.one="{{ include "slapd.usersOU" . }}" read
      by * break

    dn: olcOverlay=memberof,olcDatabase={3}mdb,cn=config
    objectClass: olcConfig
    objectClass: olcMemberOf
    objectClass: olcOverlayConfig
    objectClass: top
    olcOverlay: memberof
    olcMemberOfRefInt: TRUE
    olcMemberOfGroupOC: groupOfMembers
    olcMemberOfMemberAD: member
    olcMemberOfMemberOfAD: memberOf

    dn: olcOverlay=refint,olcDatabase={3}mdb,cn=config
    objectClass: olcConfig
    objectClass: olcRefintConfig
    objectClass: olcOverlayConfig
    objectClass: top
    olcOverlay: refint
    olcRefintAttribute: member memberOf

    dn: olcOverlay=accesslog,olcDatabase={3}mdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcAccessLogConfig
    olcOverlay: accesslog
    olcAccessLogDB: cn=accesslog
    olcAccessLogOps: writes
    olcAccessLogSuccess: TRUE
    olcAccessLogPurge: 07+00:00 01+00:00

    dn: olcOverlay=syncprov,olcDatabase={3}mdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcSyncProvConfig
    olcOverlay: syncprov
    olcSpCheckpoint: 100 10
    olcSpSessionLog: 100
