{{- $ca := genCA "slapd" 3650 }}
{{- $cert := genSignedCert (include "slapd.commonName" .) nil (list (include "slapd.commonName" .)) 1825 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slapd.serviceAccountName" . }}-internal
  labels:
    {{- include "slapd.labels" . | nindent 4 }}
type: Opaque
data:
  ca.pem: {{ $ca.Cert | b64enc | quote }}
  cert.pem: {{ printf "%s\n%s" $cert.Cert $cert.Key | b64enc | quote }}
