apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "slapd.fullname" . }}
  labels:
    {{- include "slapd.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "slapd.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "slapd.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: {{ .Values.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "slapd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "slapd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: secret
          secret:
            secretName: {{ include "slapd.fullname" . }}
            defaultMode: 0400
        - name: etc
          emptyDir: {}
        - name: run
          emptyDir: {}
      initContainers:
        - name: init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              add:
                - DAC_OVERRIDE
                - CHOWN
                - FOWNER
              drop:
                - all
          command:
            - /bin/sh
          args:
            - -c
            - >-
              mkdir -p /var/lib/ldap/accesslog
              && chown -R 10000:10000 /var/lib/ldap \
              && chmod 0700 /var/lib/ldap /var/lib/ldap/accesslog \
              && rm -rf /etc/ldap/slapd.d/*
          volumeMounts:
            - name: {{ include "slapd.fullname" . }}
              mountPath: /var/lib/ldap
            - name: etc
              mountPath: /etc/ldap/slapd.d
            - name: run
              mountPath: /run/slapd
            - name: secret
              mountPath: /secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/ldap-attr.sh
                - cn=Time,cn=Monitor
                - cn=Uptime
                - monitoredInfo
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/ldap-attr.sh
                - cn=Time,cn=Monitor
                - cn=Uptime
                - monitoredInfo
          volumeMounts:
            - name: data
              mountPath: /var/lib/ldap
            - name: etc
              mountPath: /etc/ldap/slapd.d
            - name: run
              mountPath: /run/slapd
            - name: secret
              mountPath: /secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
