apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "slapd.fullname" . }}
  labels:
    {{- include "slapd.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "slapd.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "slapd.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "slapd.fullname" . }}
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: {{ .Values.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "slapd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "slapd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: certs-external
          secret:
            secretName: {{ include "slapd.fullname" . }}-internal
            defaultMode: 0400
        - name: certs-internal
          secret:
            secretName: {{ include "slapd.fullname" . }}-internal
            defaultMode: 0400
        - name: config
          configMap:
            name: {{ include "slapd.fullname" . }}
            defaultMode: 0400
        - name: etc
          emptyDir: {}
        - name: run
          emptyDir: {}
      initContainers:
        - name: init-volumes
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              add:
                - DAC_OVERRIDE
                - CHOWN
                - FOWNER
              drop:
                - all
          command:
            - /usr/local/bin/init-volumes
          volumeMounts:
            - name: {{ include "slapd.fullname" . }}
              mountPath: /data
            - name: etc
              mountPath: /etc/ldap/slapd.d
            - name: run
              mountPath: /run/slapd
        - name: init-config
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/init-config
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: {{ include "slapd.fullname" . }}
              mountPath: /data
            - name: etc
              mountPath: /etc/ldap/slapd.d
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/exec-slapd
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "slapd.fullname" . }}
              mountPath: /data
            - name: etc
              mountPath: /etc/ldap/slapd.d
            - name: run
              mountPath: /run/slapd
        - name: haproxy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/exec-haproxy
          ports:
            - name: ldaps
              containerPort: 10636
              protocol: TCP
            - name: ldaps-syncrepl
              containerPort: 10637
              protocol: TCP
          volumeMounts:
            - name: certs-external
              mountPath: /certs/external
              readOnly: true
            - name: certs-internal
              mountPath: /certs/internal
              readOnly: true
            - name: config
              mountPath: /config
              readOnly: true
            - name: run
              mountPath: /run/slapd
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
