apiVersion: v1
kind: Service
metadata:
  name: {{ include "slapd.fullname" . }}
  labels:
    {{- include "slapd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ldaps
      protocol: TCP
      name: ldaps
  selector:
    {{- include "slapd.selectorLabels" . | nindent 4 }}
